### PR TITLE
Show help by default when no arguments provided

### LINKED ISSUE #20: CLI: show help by default when running with no arguments

### PR DESCRIPTION
**Pull request by tanmayrajani**
Closes #20

### CODE REVIEW

**Comment by danburzo** [comment]
Also, we've started splitting the CLI into a separate `cli.js` file; sorry for breaking your PR :-) Can you put it in `cli.js` instead?

**Comment by tanmayrajani** [comment]
Yes, fortunately, I was watching the repo and knew those changes! :)

**Comment by tanmayrajani** [comment]
There seems to be some issues with the default command in commander but I've figured that the changes I ended up with in above commit works just right. Let me know your opinion/suggestions

**Comment by danburzo** [comment]
Let's merge it as-is for now. It would be great to raise an issue with commander.js to get a second opinion on how to best achieve this.

**Comment by danburzo** [comment]
Thank you for the contribution!

**Pull request merged**
