### PR TITLE
#88 feature adds exif data to pdf file

### LINKED ISSUE #88: PDF: Fill in metadata
Would be useful.
https://github.com/GoogleChrome/puppeteer/issues/3054

### PR DESCRIPTION
**Pull request by yashha**
- it uses cli params or title and author of first document
- adds --author -a cli param for cover and exif data

closes #88

### CODE REVIEW

**Comment by danburzo** [comment]
Thank you for this. 

Would you be interested in exploring [pdf-lib](https://github.com/Hopding/pdf-lib) as an alternative library for this purpose? 

I'd like percollate to use as few external binaries as possible (since Puppeteer already causes installation problems on various platforms) and opt for a more targeted, Node-native PDF library.

**Comment by danburzo** [comment]
This is very cool, I'm glad pdf-lib works well for this! 

Functionally, the one thing I'd adjust is write the PDF to the disk just once. In puppetteer's [`pdf()` method](https://github.com/puppeteer/puppeteer/blob/v5.3.1/docs/api.md#pagepdfoptions), when you omit the `path` option, you get a Buffer instead of it writing to the disk, and you can pass that Buffer to PDFDocument to make the metadata changes, then finally write it to `output_path` in `bundlePDF`.

(I can also do this after merging into master, if you prefer)

**Comment by yashha** [comment]
Sure, I prefer you doing it, sounds like you have a plan :)

**Comment by danburzo** [comment]
Awesome, thanks again!

**Pull request merged**
