### PR TITLE
Adds unit tests [WIP]

### LINKED ISSUE #11: Add tests

### PR DESCRIPTION
**Pull request by phenax**
# Work In Progress - (DO NOT MERGE)

Fixes #11 

## Changes
* Adds test cases
* Refactors code

### CODE REVIEW

**Comment by danburzo** [comment]
Sorry for the late response. This is a very solid effort! I wonder how we should proceed to get the tests in the codebase as soon as possible, so you're not stuck merging conflicts for the foreseeable future :-)

**Comment by danburzo** [comment]
Hi @phenax, if it's okay with you, I'll take your changes locally and adapt the tests to the current codebase.

**Comment by phenax** [comment]
Sure. Let me know if I can help.

**Comment by danburzo** [comment]
Thank you again, @phenax! I've pulled in on `master` some of the tests that make sense on the current codebase.

**Pull request merged**
